### ISSUE TITLE
Newest version at SourceForge

### ISSUE THREAD

**Issue by skamila** [FranklinDM/SimPE#3]
Hi! Could you share newest version of SimPE at SourceForge? There is some newer version of your software but it is not obvious from with source you can download it safe - sims.ambertation.de is not longer available and version at SourceForge is very old and works only with Kitchen & Bath Interior Design Stuff. 
There is still a lot of people who download SimPE from SourceForge so maybe you can upload the newest version there :)

**Comment by fofajardo** [comment]
Unfortunately, I don't have control over the SimPE repository at SourceForge, so there's nothing that I can do about it.
